### ISSUE TITLE
CheckError

### ISSUE THREAD

**Issue by wqy1994123** [amazon-research/FeatGraph#9]
Traceback (most recent call last):
  File "bench_vanilla_spmm.py", line 82, in <module>
    bench_vanilla_spmm_x86(adj_scipy_csr, args.feat_len)
  File "bench_vanilla_spmm.py", line 41, in bench_vanilla_spmm_x86
    _bench_vanilla_spmm_x86(num_col_partitions, num_feat_partitions)
  File "bench_vanilla_spmm.py", line 33, in _bench_vanilla_spmm_x86
    tcost = vanilla_spmm_module.measure_average_time(input_tvm_ndarrays, num_runs)
  File "\pythonProject\FeatGraph2\python\featgraph\module\spmm.py", line 179, in measure_average_time
    timer = self._func.time_evaluator(self._func.entry_name, ctx=self._ctx, number=num_runs)
  File "\Python\Python37\site-packages\tvm-0.7.0-py3.7-win-amd64.egg\tvm\runtime\module.py", line 220, in time_evaluator
    f_preproc,
  File "\Python\Python37\site-packages\tvm-0.7.0-py3.7-win-amd64.egg\tvm\_ffi\_ctypes\packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "\tvm0.7\tvm\src\target\llvm\llvm_module.cc", line 79
TVMError: Check failed: entry_name != nullptr: Symbol __tvm_main__ is not presented
I meet this error when I run all benchmark scripts.
Is there something wrong with tvm0.7?Could you help me?

**Comment by Huyuwei** [comment]
I can run FeatGraph with tvm v0.7. Could you first confirm that you have successfully installed TVM? You can run this tutorial http://tvm.apache.org/docs/tutorials/get_started/tensor_expr_get_started.html

**Comment by wqy1994123** [comment]
it seems tvm isn't installed correctly,thank you so much
